"""
OmniEngine — Agent State Schema

Defines the LangGraph state graph schema using TypedDict with
annotated reducers. This state flows through every node in the
orchestrator and is checkpointed to Redis for recovery.
"""

import operator
from typing import Annotated, Any, Literal, TypedDict

from langchain_core.messages import AnyMessage


def _merge_dicts(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    """Merge two dicts, with right overwriting left on key conflicts."""
    merged = {**left}
    merged.update(right)
    return merged


def _replace(left: Any, right: Any) -> Any:  # noqa: ARG001
    """Reducer that always takes the latest value."""
    return right


class TaskStep(TypedDict):
    """A single step in a task plan generated by the Planner."""

    step_id: int
    description: str
    tool: str | None  # Tool to use, or None for direct LLM response
    model_tier: Literal["small", "medium", "large", "reasoning"]
    success_criteria: str
    status: Literal["pending", "in_progress", "completed", "failed"]
    result: str | None
    retries: int


class AgentState(TypedDict):
    """
    Global state for the LangGraph orchestrator.

    Every node reads from and writes to this state. Fields use annotated
    reducers to control how concurrent updates are merged.

    Key design decisions:
      - `messages` uses operator.add to append (standard LangGraph pattern)
      - `scratchpad` accumulates internal reasoning (hidden from user)
      - `current_plan` is replaced wholesale when re-planning occurs
      - `metadata` is merged (dict union)
    """

    # --- Core ---
    session_id: str
    messages: Annotated[list[AnyMessage], operator.add]

    # --- Internal Reasoning (Hidden from user) ---
    scratchpad: Annotated[list[dict[str, Any]], operator.add]
    internal_monologue: Annotated[str, _replace]

    # --- Planning ---
    current_plan: Annotated[list[TaskStep], _replace]
    current_step_index: Annotated[int, _replace]
    plan_iteration: Annotated[int, _replace]  # Number of re-plans

    # --- Tool State ---
    active_tools: Annotated[list[str], _replace]
    tool_call_count: Annotated[int, _replace]
    consecutive_tool_failures: Annotated[int, _replace]
    pending_tool_calls: Annotated[list[dict[str, Any]], _replace]

    # --- Safety ---
    safety_flags: Annotated[list[str], operator.add]
    confidence_score: Annotated[float | None, _replace]

    # --- Routing ---
    model_used: Annotated[str, _replace]
    model_tier: Annotated[str, _replace]

    # --- Performance ---
    latency_metrics: Annotated[dict[str, float], _merge_dicts]
    total_tokens: Annotated[int, _replace]
    total_cost_usd: Annotated[float, _replace]

    # --- Control Flow ---
    next_node: Annotated[str, _replace]  # Used for conditional routing
    should_respond: Annotated[bool, _replace]  # True when ready to emit response
    is_done: Annotated[bool, _replace]

    # --- Metadata ---
    metadata: Annotated[dict[str, Any], _merge_dicts]
    user_message: Annotated[str, _replace]
    attachments: Annotated[list[dict[str, Any]], _replace]
    model_preference: Annotated[str | None, _replace]
    temperature: Annotated[float | None, _replace]

    # --- Memory Context ---
    retrieved_memories: Annotated[list[dict[str, Any]], _replace]
    context_summary: Annotated[str | None, _replace]


def create_initial_state(
    session_id: str,
    user_message: str,
    attachments: list[dict[str, Any]] | None = None,
    model_preference: str | None = None,
    temperature: float | None = None,
) -> AgentState:
    """
    Create a fresh AgentState for a new request.

    This is called at the start of each chat invocation. The state
    is populated with defaults and the user's input.
    """
    return AgentState(
        session_id=session_id,
        messages=[],
        scratchpad=[],
        internal_monologue="",
        current_plan=[],
        current_step_index=0,
        plan_iteration=0,
        active_tools=[],
        tool_call_count=0,
        consecutive_tool_failures=0,
        pending_tool_calls=[],
        safety_flags=[],
        confidence_score=None,
        model_used="",
        model_tier="medium",
        latency_metrics={},
        total_tokens=0,
        total_cost_usd=0.0,
        next_node="supervisor",
        should_respond=False,
        is_done=False,
        metadata={},
        user_message=user_message,
        attachments=attachments or [],
        model_preference=model_preference,
        temperature=temperature,
        retrieved_memories=[],
        context_summary=None,
    )
